---
title: "Coastal Population"
author: "Derek Corcoran"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#library(rgee)
library(terra)
library(rworldxtra)
library(tidyterra)
library(tidyverse)
```


```{r Other, include=FALSE}
data("countriesHigh")
```


```{r WorldBuild, cache = T}

World <- terra::vect(countriesHigh)

World$World <- "Yes"

World <- World[,"World"]

World <- terra::makeValid(World)

World <- terra::aggregate(World, by = "World", cores = 3)

World <- terra::fillHoles(World) %>% terra::project("+proj=moll")

World <- terra::makeValid(World)

World <- World[,"World"]

World_Inner <- terra::buffer(World, width = -100000)

World_Inner <- terra::makeValid(World_Inner)

Coastal_World <- erase(World, World_Inner)
```

```{r Areas, cache = T}
CoastalArea <- terra::expanse(Coastal_World, unit = "km", transform=F)
InnerArea <- terra::expanse(World_Inner, unit = "km", transform=F)
WorldArea <- terra::expanse(World, unit = "km", transform=F)
```



```{r, cache = T}
ggplot() + geom_spatvector(data = World, fill = "green") + theme_bw() + ggtitle("World")
```

The World area is `r prettyNum(WorldArea, big.mark = ",")` sq km

```{r, cache = T}
ggplot() + geom_spatvector(data = Coastal_World, fill = "green") + theme_bw() + ggtitle("Coastal")
```

The Costal area is `r prettyNum(CoastalArea, big.mark = ",")` sq km, that is  `r round(((CoastalArea/WorldArea)*100), 2)` percent of the world

```{r, cache = T}
ggplot() + geom_spatvector(data = World_Inner, fill = "green") + theme_bw() + ggtitle("Inner")
```

The Inner area is `r prettyNum(InnerArea, big.mark = ",")`, that is  `r round(((InnerArea/WorldArea)*100), 2)` percent of the world

```{r, eval = F}
terra::writeVector(World_Inner, "WorldInner.shp", overwrite = T)
terra::writeVector(Coastal_World, "CoastalWorld.shp", overwrite = T)
```

